version: '3.1'

services:
  dev_dc:
    container_name: netcore
    # build: .
    image: binacslee/deployment-csharp-dev
    privileged: true
    environment:
      - PASSWORD=test
    volumes:
      - .:/gitpro
    ports:
      - 10000:8443
